config/routes.rb
Rails.application.routes.draw do
  resources :mail_contacts
  devise_for :users
  get 'single/index'
  post 'single/send_email'
  resources :entry_pages
  resources :sections
  resources :companies

  root "single#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mail_contact.rb
class MailContact < ApplicationRecord
end

app/controllers/mail_contacts_controller.rb
class MailContactsController < ApplicationController
  before_action :set_mail_contact, only: [:show, :edit, :update, :destroy]

  # GET /mail_contacts
  # GET /mail_contacts.json
  def index
    @mail_contacts = MailContact.all
  end

  # GET /mail_contacts/1
  # GET /mail_contacts/1.json
  def show
  end

  # GET /mail_contacts/new
  def new
    @mail_contact = MailContact.new
  end

  # GET /mail_contacts/1/edit
  def edit
  end

  # POST /mail_contacts
  # POST /mail_contacts.json
  def create
    @mail_contact = MailContact.new(mail_contact_params)

    respond_to do |format|
      if @mail_contact.save
        format.html { redirect_to @mail_contact, notice: 'Tu mensaje fue enviado con éxito' }
        format.json { render :show, status: :created, location: @mail_contact }
      else
        format.html { render :new }
        format.json { render json: @mail_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mail_contacts/1
  # PATCH/PUT /mail_contacts/1.json
  def update
    respond_to do |format|
      if @mail_contact.update(mail_contact_params)
        format.html { redirect_to @mail_contact, notice: 'Mail contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @mail_contact }
      else
        format.html { render :edit }
        format.json { render json: @mail_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_contacts/1
  # DELETE /mail_contacts/1.json
  def destroy
    @mail_contact.destroy
    respond_to do |format|
      format.html { redirect_to mail_contacts_url, notice: 'Mail contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mail_contact
      @mail_contact = MailContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mail_contact_params
      params.require(:mail_contact).permit(:name, :email, :question, :already_read, :already_answered)
    end
end

app/helpers/mail_contacts_helper.rb
module MailContactsHelper
end

app/views/mail_contacts/_form.html.erb
<%= form_for(mail_contact) do |f| %>
  <% if mail_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mail_contact.errors.count, "error") %> prohibited this mail_contact from being saved:</h2>

      <ul>
      <% mail_contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_field :question %>
  </div>

  <div class="field">
    <%= f.label :already_read %>
    <%= f.check_box :already_read %>
  </div>

  <div class="field">
    <%= f.label :already_answered %>
    <%= f.check_box :already_answered %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mail_contacts/edit.html.erb
<h1>Editing Mail Contact</h1>

<%= render 'form', mail_contact: @mail_contact %>

<%= link_to 'Show', @mail_contact %> |
<%= link_to 'Back', mail_contacts_path %>

app/views/mail_contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mail Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Question</th>
      <th>Already read</th>
      <th>Already answered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mail_contacts.each do |mail_contact| %>
      <tr>
        <td><%= mail_contact.name %></td>
        <td><%= mail_contact.email %></td>
        <td><%= mail_contact.question %></td>
        <td><%= mail_contact.already_read %></td>
        <td><%= mail_contact.already_answered %></td>
        <td><%= link_to 'Show', mail_contact %></td>
        <td><%= link_to 'Edit', edit_mail_contact_path(mail_contact) %></td>
        <td><%= link_to 'Destroy', mail_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mail Contact', new_mail_contact_path %>

app/views/mail_contacts/new.html.erb
<h1>New Mail Contact</h1>

<%= render 'form', mail_contact: @mail_contact %>

<%= link_to 'Back', mail_contacts_path %>

app/views/mail_contacts/show.html.erb
<p id="notice">Your message was delivered successfully!</p>


<%= link_to 'Back to home', root_path %>