config/routes.rb
Rails.application.routes.draw do
  resources :mail_contacts
  devise_for :users
  get 'single/index'
  post 'single/send_email'
  resources :entry_pages
  resources :sections
  resources :companies

  root "single#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :sections
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :logo, :headline, :address, :phone1, :phone2, :lat, :lng, :active,:homepage)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :logo %>
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :homepage %>
    <%= f.text_area :homepage %>
  </div>
  <div class="field">
    <%= f.label :headline %>
    <%= f.text_field :headline %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone1 %>
    <%= f.text_field :phone1 %>
  </div>

  <div class="field">
    <%= f.label :phone2 %>
    <%= f.text_field :phone2 %>
  </div>

  <div class="field">
    <%= f.label :lat %>
    <%= f.text_field :lat %>
  </div>

  <div class="field">
    <%= f.label :lng %>
    <%= f.text_field :lng %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th>Headline</th>
      <th>Address</th>
      <th>Phone1</th>
      <th>Phone2</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.logo %></td>
        <td><%= company.headline %></td>
        <td><%= company.address %></td>
        <td><%= company.phone1 %></td>
        <td><%= company.phone2 %></td>
        <td><%= company.lat %></td>
        <td><%= company.lng %></td>
        <td><%= company.active %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @company.logo %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @company.headline %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Phone1:</strong>
  <%= @company.phone1 %>
</p>

<p>
  <strong>Phone2:</strong>
  <%= @company.phone2 %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @company.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @company.lng %>
</p>

<p>
  <strong>Active:</strong>
  <%= @company.active %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>