config/routes.rb
Rails.application.routes.draw do
  resources :mail_contacts
  devise_for :users
  get 'single/index'
  post 'single/send_email'
  resources :entry_pages
  resources :sections
  resources :companies

  root "single#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entry_page.rb
class EntryPage < ApplicationRecord
  belongs_to :section

    scope :published, ->{ where("published = ?", true) }
end

app/controllers/entry_pages_controller.rb
class EntryPagesController < ApplicationController
  before_action :set_entry_page, only: [:show, :edit, :update, :destroy]

  # GET /entry_pages
  # GET /entry_pages.json
  def index
    @entry_pages = EntryPage.all
  end

  # GET /entry_pages/1
  # GET /entry_pages/1.json
  def show
  end

  # GET /entry_pages/new
  def new
    @entry_page = EntryPage.new
  end

  # GET /entry_pages/1/edit
  def edit
  end

  # POST /entry_pages
  # POST /entry_pages.json
  def create
    @entry_page = EntryPage.new(entry_page_params)

    respond_to do |format|
      if @entry_page.save
        format.html { redirect_to @entry_page, notice: 'Entry page was successfully created.' }
        format.json { render :show, status: :created, location: @entry_page }
      else
        format.html { render :new }
        format.json { render json: @entry_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entry_pages/1
  # PATCH/PUT /entry_pages/1.json
  def update
    respond_to do |format|
      if @entry_page.update(entry_page_params)
        format.html { redirect_to @entry_page, notice: 'Entry page was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry_page }
      else
        format.html { render :edit }
        format.json { render json: @entry_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entry_pages/1
  # DELETE /entry_pages/1.json
  def destroy
    @entry_page.destroy
    respond_to do |format|
      format.html { redirect_to entry_pages_url, notice: 'Entry page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry_page
      @entry_page = EntryPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_page_params
      params.require(:entry_page).permit(:title, :body, :published, :section_id)
    end
end

app/helpers/entry_pages_helper.rb
module EntryPagesHelper
end

app/views/entry_pages/_form.html.erb
<%= form_for(entry_page) do |f| %>
  <% if entry_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry_page.errors.count, "error") %> prohibited this entry_page from being saved:</h2>

      <ul>
      <% entry_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>

  <div class="field">
    <%= f.label :section_id %>
    <%= f.text_field :section_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entry_pages/edit.html.erb
<h1>Editing Entry Page</h1>

<%= render 'form', entry_page: @entry_page %>

<%= link_to 'Show', @entry_page %> |
<%= link_to 'Back', entry_pages_path %>

app/views/entry_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entry Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Published</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entry_pages.each do |entry_page| %>
      <tr>
        <td><%= entry_page.title %></td>
        <td><%= entry_page.body %></td>
        <td><%= entry_page.published %></td>
        <td><%= entry_page.section %></td>
        <td><%= link_to 'Show', entry_page %></td>
        <td><%= link_to 'Edit', edit_entry_page_path(entry_page) %></td>
        <td><%= link_to 'Destroy', entry_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry Page', new_entry_page_path %>

app/views/entry_pages/new.html.erb
<h1>New Entry Page</h1>

<%= render 'form', entry_page: @entry_page %>

<%= link_to 'Back', entry_pages_path %>

app/views/entry_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @entry_page.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @entry_page.body %>
</p>

<p>
  <strong>Published:</strong>
  <%= @entry_page.published %>
</p>

<p>
  <strong>Section:</strong>
  <%= @entry_page.section %>
</p>

<%= link_to 'Edit', edit_entry_page_path(@entry_page) %> |
<%= link_to 'Back', entry_pages_path %>